schema:
    namespaces:
        ontology: https://vocabs.acdh.oeaw.ac.at/schema#
    ontology:
      order: https://vocabs.acdh.oeaw.ac.at/schema#ordering
      recommended: https://vocabs.acdh.oeaw.ac.at/schema#recommendedClass
      langTag: https://vocabs.acdh.oeaw.ac.at/schema#langTag
      vocabs: https://vocabs.acdh.oeaw.ac.at/schema#vocabs
composerLocation: ./vendor/autoload.php

