name: check

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: composer
      run: composer update
    - name: check
      run: vendor/acdh-oeaw/arche-schema-ingest/checkOntology.php config.yaml acdh-schema.owl

