name: check

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: composer
      run: composer update
    - name: check
      run: vendor/bin/arche-check-ontology https://arche.acdh.oeaw.ac.at/api/ acdh-schema.owl

